# Generated by Django 4.1 on 2023-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TeamName", models.CharField(max_length=255)),
                ("Leader", models.CharField(max_length=255)),
                ("TeamMembers", models.CharField(max_length=255)),
                ("LeaderNumber", models.CharField(max_length=255)),
                ("TeamNumbers", models.CharField(max_length=255)),
                ("LeaderEmail", models.CharField(max_length=255)),
                ("TeamEmail", models.CharField(max_length=255)),
                ("TeamDomain", models.CharField(max_length=255)),
                ("CollegeName", models.CharField(max_length=255)),
                ("Year", models.CharField(max_length=255)),
                ("PaymentSS", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
