# Generated by Django 4.1 on 2023-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="id",
        ),
        migrations.AddField(
            model_name="team",
            name="TeamID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
