# Generated by Django 4.1.7 on 2023-03-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_team_id_team_teamid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="TeamDomain",
        ),
        migrations.RemoveField(
            model_name="team",
            name="TeamEmail",
        ),
        migrations.RemoveField(
            model_name="team",
            name="TeamMembers",
        ),
        migrations.RemoveField(
            model_name="team",
            name="TeamNumbers",
        ),
        migrations.RemoveField(
            model_name="team",
            name="Year",
        ),
        migrations.AddField(
            model_name="team",
            name="EventsRegistered",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
    ]
