# Generated by Django 4.1.7 on 2023-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_escaperoomteam_nerfarenateam_technovateam_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechAThonTeam",
            fields=[
                ("TeamID", models.AutoField(primary_key=True, serialize=False)),
                ("TeamName", models.CharField(max_length=255)),
                ("Leader", models.CharField(max_length=255)),
                ("LeaderNumber", models.CharField(max_length=255)),
                ("LeaderEmail", models.CharField(max_length=255)),
                ("PaymentSS", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="TechNovationTeam",
        ),
        migrations.AddField(
            model_name="technovateam",
            name="abstract",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technovateam",
            name="domain",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technovateam",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
